export const experienceList = [
   {
    id: 1,
    companyName: "TREATMENT TRAVELLER",
    period: "Nov 2023 - Currently working",
    position: "Web Developer",
    location: "Noida, Uttar Pradesh, India",
    skills: [
      "React JS",
      "JavaScript",
      "HTML",
      "Redux",
      "Git",
      "Next.js",
      "TypeScript",
      "CSS",
      "jQuery",
      "GitHub",
      "Material UI",
      "Ant Design",
      "Tailwind CSS",
      "Figma",
      "REST API",
    ],
    logo: "/ttLogo.png",
  },
  {
    id: 2,
    companyName: "ELEVERA TECHNOLOGIES",
    period: "Jul 2022 - Jun 2023 · 1 yr",
    position: "Programmer Analyst",
    location: "Jamshedpur, India",
    skills: [
      "React JS",
      "JavaScript",
      "HTML",
      "Redux",
      "Git",
      "Next.js",
      "TypeScript",
      "CSS",
      "jQuery",
      "GitHub",
      "Material UI",
      "Ant Design",
      "Tailwind CSS",
      "Figma",
      "REST API",
    ],
    logo: "/eleveratech.png",
  },
  {
    id: 3,
    companyName: "ADITYAPUR AUTO-CLUSTER ",
    period: "Jul 2021 - Dec 2021 ·  6 mos",
    position: "Web Developer Intern",
    location: "Jamshedpur,Jharkhand, India",
    skills: [
      "React JS",
      "JavaScript",
      "HTML",
      "Redux",
      "Git",
      "Next.js",
      "TypeScript",
      "CSS",
      "jQuery",
      "GitHub",
      "Material UI",
      "Ant Design",
      "Tailwind CSS",
      "Figma",
      "REST API",
    ],
    logo: "/adityapur-auto-cluster-logo.png",
  },
  // {
  //   id: 4,
  //   companyName: "Schneider Electric · Internship",
  //   period: "Oct 2019 - Nov 2019 · 2 mos",
  //   position: "Web Developer",
  //   location: "Chennai, Tamil Nadu, India",
  //   skills: ["JavaScript", "HTML", "Git", "REST API"],
  //   logo: "/schneider.jpeg",
  // },
  
];
